# Generated by Django 4.1 on 2025-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
