# Generated by Django 4.1 on 2025-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_rent_total_rent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_master',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_master_user',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='Home.order_master_user'),
            preserve_default=False,
        ),
    ]
