# Generated by Django 4.1 on 2025-05-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_payment_order_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_master_user',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_master',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
