# Generated by Django 4.1 on 2025-05-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_payment_order_master_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_seller',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('order_master_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.order_master_seller')),
            ],
        ),
        migrations.CreateModel(
            name='payment_user',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('order_master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.order_master_user')),
            ],
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
